import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Nav from "./auth/Nav";
import QueryWrapper from "./auth/QueryWrapper";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Gamer Spot",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col  ${roboto.variable} bg-gradient-to-tl from-blue-800 via-purple-700 to-pink-800`}
      >
        <QueryWrapper>
          <Toaster />
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  );
}
